---
kind: pipeline
type: docker
name: terraform-provider-couchbase

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: linter
    image: golang:latest
    commands:
      - apt-get update && apt-get install -y python3-pip shellcheck build-essential
      - pip3 install yamllint --break-system-packages
      - go install "golang.org/x/lint/golint@latest"
      - make linters

  - name: run tests
    image: golang:latest
    commands:
      - make cbinit
      - make test
      - make testacc
    environment:
      CB_ADDRESS: couchbase
      CB_CLIENT_PORT: 8091
      CB_NODE_PORT: 11210
      CB_PASSWORD: 123456
      CB_USERNAME: Administrator

services:
  - name: couchbase
    image: couchbase

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - tag

---
kind: signature
hmac: 8cd1dce2ce3da844850c535abba88b84ad6317a3764897ea9096c76c2fd776c7

...
