---
name: linters

on:
  workflow_call:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  pull-requests: write
  statuses: write


jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v6.9.0
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
