---
name: main branch tests

on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Linters
        uses: ./.github/workflows/linters.yml  
      - name: Tests
        uses: ./.github/workflows/tests.yml
