---
name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linters:
    uses: ./.github/workflows/linters.yml  
  tests:
    uses: ./.github/workflows/tests.yml
  goreleaser:
    runs-on: ubuntu-latest
    needs: [linters, tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
